using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using VertiCore.Application.Interfaces.Services;
using VertiCore.Application.Interfaces.Repositories;
using VertiCore.Infrastructure.Data;
using VertiCore.Domain.Exceptions;

namespace VertiCore.Infrastructure.Services
{
    public class PdfService : IPdfService
    {
        private readonly AppDbContext _context;

        public PdfService(AppDbContext context)
        {
            QuestPDF.Settings.License = LicenseType.Community;
            _context = context;
        }

        public byte[] GenerateInvoicePdf(Guid invoiceId, Guid tenantId)
        {
            var invoice = _context.Invoices.FirstOrDefault(item => item.Id == invoiceId && item.TenantId == tenantId);
            if (invoice == null)
                throw new InvoiceNotFoundException(invoiceId);

            var client = _context.Clients.FirstOrDefault(item =>
                item.Id == invoice.ClientId && item.TenantId == tenantId);

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);

                    page.Header().Text($"Invoice {invoice.InvoiceNumber}")
                        .FontSize(20).Bold();

                    page.Content().Column(column =>
                    {
                        column.Item().Text($"Client: {client?.FullName}");
                        column.Item().Text($"Due Date: {invoice.DueDate:dd MMM yyyy}");
                        column.Item().Text($"Status: {invoice.Status}");
                        column.Item().Text($"Total Amount: PKR {invoice.TotalAmount:N2}");
                        column.Item().Text($"Notes: {invoice.Notes}");
                    });

                    page.Footer().AlignCenter().Text("Generated by VertiCore");
                });
            });

            return document.GeneratePdf();
        }
    }
}

