using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using VertiCore.Application.Interfaces;
using VertiCore.Infrastructure.Data;

namespace VertiCore.Infrastructure.Services
{
    public class PdfService : IPdfService
    {
        private readonly AppDbContext _context;

        public PdfService(AppDbContext context)
        {
            QuestPDF.Settings.License = LicenseType.Community;
            _context = context;
        }

        public byte[] GenerateInvoicePdf(Guid invoiceId)
        {
            var invoice = _context.Invoices.Find(invoiceId);
            if (invoice == null)
                throw new KeyNotFoundException("Invoice not found");

            var client = _context.Clients.Find(invoice.ClientId);

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);

                    page.Header().Text($"Invoice {invoice.InvoiceNumber}")
                        .FontSize(20).Bold();

                    page.Content().Column(column =>
                    {
                        column.Item().Text($"Client: {client?.FullName}");
                        column.Item().Text($"Due Date: {invoice.DueDate:dd MMM yyyy}");
                        column.Item().Text($"Status: {invoice.Status}");
                        column.Item().Text($"Total Amount: PKR {invoice.TotalAmount:N0}");
                        column.Item().Text($"Notes: {invoice.Notes}");
                    });

                    page.Footer().AlignCenter().Text("Generated by VertiCore");
                });
            });

            return document.GeneratePdf();
        }
    }
}
